DROP DATABASE IF EXISTS ttschool;
CREATE DATABASE `ttschool`;
USE `ttschool`;

CREATE TABLE trainee (
    id INT(11) NOT NULL AUTO_INCREMENT,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    rating INT(11) NOT NULL,
    groupId INT DEFAULT NULL,
    PRIMARY KEY (id),
      FOREIGN KEY (groupId) REFERENCES `group` (id) ON DELETE SET NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE subject (
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `group` (
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    room VARCHAR(50) NOT NULL,
    schoolId INT(11) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (schoolId) REFERENCES school (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE school (
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    year INT(11) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY (name, year)
) ENGINE=INNODB DEFAULT CHARSET=utf8;


